[syn]
exclude = ["ExprReference", "token::*"]

[proc-macro2]
exclude = ["TokenTree"]

[serde_json]
exclude = ["Value"]

[hashbrown]
exclude = [
   "hash_map::Entry", # Need a custom bound on K: Borrow<Q>
   "hash_map::EntryRef"
]

[kdl]
exclude = ["KdlValue"] # We can be cleverer

[aws-sdk-ec2]
[aws-smithy-types]
[bytes]
[dashmap]
[miette]
[rustdoc-types]
[smallvec]