[package]
name = "debug3"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Space Efficient Pretty Printer"
repository = "https://github.com/aDotInTheVoid/debug3/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
dashmap = "5.2.0"
debug3-derive = { version = "0.1.0", path = "derive" }
hashbrown = "0.12.0"

# Thinks we impl for
proc-macro2 = {version = "1.0.37", features = ["span-locations"] }
rustdoc-types = "0.10.0"
serde_json = "1.0.79"
smallvec = { version = "1.8.0", features = ["const_generics"] }
syn = { version = "1.0.91", optional = false, features = ["full"] }

[workspace]
members = [
    ".",
    "./derive"
]

exclude = ["generator"]

[dev-dependencies]
trybuild = "1.0.56"
rustversion = "1.0.6"
serde_json = "1.0.79"
expect-test = "1.2.2"
fxhash = "0.2.1"

[features]
