[package]
name = "debug3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debug3-derive = { version = "0.1", path = "derive" }
rustversion = "1.0.6"

[workspace]
members = [
    ".",
    "./derive"
]

[dev-dependencies]
trybuild = "1.0.56"
