// AUTOGENERATED FILE, DO NOT EDIT
//
// Crate Name: `bytes`
// Crate Version: `1.3.0`
// Skipping bytes::Bytes due to hidden fields
// Skipping bytes::BytesMut due to hidden fields
// Skipping bytes::buf::Chain due to hidden fields
// Skipping bytes::buf::IntoIter due to hidden fields
// Skipping bytes::buf::Limit due to hidden fields
// Skipping bytes::buf::Reader due to hidden fields
// Skipping bytes::buf::Take due to hidden fields
// Skipping bytes::buf::UninitSlice due to hidden fields
// Skipping bytes::buf::Writer due to hidden fields
