// AUTOGENERATED FILE, DO NOT EDIT
//
// Crate Name: `kdl`
// Crate Version: `4.3.0`
// Skipping kdl::KdlDocument due to hidden fields
// Skipping kdl::KdlEntry due to hidden fields
impl crate::Debug for kdl::KdlError {
    fn fmt(&self, f: &mut crate::Formatter) {
        f.debug_struct("KdlError")
            .field("input", &self.input)
            .field("span", &self.span)
            .field("label", &self.label)
            .field("help", &self.help)
            .field("kind", &self.kind)
            .finish()
    }
}
impl crate::Debug for kdl::KdlErrorKind {
    fn fmt(&self, f: &mut crate::Formatter) {
        match self {
            Self::ParseIntError(__0) => {
                f.debug_tuple("ParseIntError").field(__0).finish();
            }
            Self::ParseFloatError(__0) => {
                f.debug_tuple("ParseFloatError").field(__0).finish();
            }
            Self::Context(__0) => {
                f.debug_tuple("Context").field(__0).finish();
            }
            Self::Other => {
                f.debug_tuple("Other").finish();
            }
        }
    }
}
// Skipping kdl::KdlIdentifier due to hidden fields
// Skipping kdl::KdlNode due to hidden fields
// Skiping kdl::KdlValue due to config rule KdlValue
impl crate::Debug for kdl::NodeKey {
    fn fmt(&self, f: &mut crate::Formatter) {
        match self {
            Self::Key(__0) => {
                f.debug_tuple("Key").field(__0).finish();
            }
            Self::Index(__0) => {
                f.debug_tuple("Index").field(__0).finish();
            }
        }
    }
}
