// AUTOGENERATED FILE, DO NOT EDIT
//
// Crate Name: `miette`
// Crate Version: `4.7.1`
// Skiping struct Some("Error") due to not having path
impl<> crate::Debug for miette::DebugReportHandler<>  where  {
    fn fmt(&self, f: &mut crate::Formatter) {
        f.debug_struct("DebugReportHandler")
            .finish()
    }
}
// Skipping miette::Error due to hidden fields
impl<> crate::Debug for miette::InstallError<>  where  {
    fn fmt(&self, f: &mut crate::Formatter) {
        f.debug_struct("InstallError")
            .finish()
    }
}
impl<> crate::Debug for miette::JSONReportHandler<>  where  {
    fn fmt(&self, f: &mut crate::Formatter) {
        f.debug_struct("JSONReportHandler")
            .finish()
    }
}
// Skipping miette::LabeledSpan due to hidden fields
impl<>  crate::Debug for miette::MietteError<> where  {
    fn fmt(&self, f: &mut crate::Formatter) {
        match self {
            Self::IoError (__0, ) => { f.debug_tuple("IoError").field(__0).finish(); }
            Self::OutOfBounds => { f.debug_tuple("OutOfBounds").finish(); }
        }
    }
}
// Skipping miette::MietteSpanContents due to hidden fields
// Skipping miette::NamedSource due to hidden fields
// Skipping miette::NarratableReportHandler due to hidden fields
impl<>  crate::Debug for miette::Severity<> where  {
    fn fmt(&self, f: &mut crate::Formatter) {
        match self {
            Self::Error => { f.debug_tuple("Error").finish(); }
            Self::Warning => { f.debug_tuple("Warning").finish(); }
            Self::Advice => { f.debug_tuple("Advice").finish(); }
        }
    }
}
// Skipping miette::SourceOffset due to hidden fields
// Skipping miette::SourceSpan due to hidden fields
