// AUTOGENERATED FILE, DO NOT EDIT
//
// Crate Name: `smallvec`
// Crate Version: `1.9.0`
impl crate::Debug for smallvec::CollectionAllocErr {
    fn fmt(&self, f: &mut crate::Formatter) {
        match self {
            Self::CapacityOverflow => {
                f.debug_tuple("CapacityOverflow").finish();
            }
            Self::AllocErr { layout } => {
                f.debug_struct("AllocErr").field("layout", layout).finish()
            }
        }
    }
}
// Skipping smallvec::Drain due to hidden fields
// Skipping smallvec::IntoIter due to hidden fields
// Skipping smallvec::SmallVec due to hidden fields
