# https://github.com/dtolnay/thiserror/blob/master/.github/workflows/ci.yml

name: CI

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [beta, stable, nightly, 1.63.0]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: rust-src
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack test --each-feature --optional-deps --tests
        env:
          RUSTFLAGS: ${{matrix.rustflags}} ${{env.RUSTFLAGS}}
      - run: cargo test --doc
        env:
          RUSTFLAGS: ${{matrix.rustflags}} ${{env.RUSTFLAGS}}        

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy --tests --all-features -- -Dclippy::all # -Dclippy::pedantic
  # We must use old miette, because thats what latest KDL Uses
  # outdated:
  #   name: Outdated
  #   runs-on: ubuntu-latest
  #   if: github.event_name != 'pull_request'
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: dtolnay/install@cargo-outdated
  #     - run: cargo outdated --exit-code 1
